version: '3.7'

services:
  proxy:
    image: nginx:alpine
    restart: always
    ports:
       - 80:80
    volumes:
      -  ./client:/opt/webrtc-app/client
      -  ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx